name: Cache Node.js Modules
description: Custom action to cache Node.js modules.
inputs:
  path:
    description: Path to cache (default is ~/.npm).
    required: false
    default: ~/.npm
  key:
    description: Cache key for Node.js modules.
    required: false

runs:
  using: "composite"
  steps:
    - name: Generate cache key
      id: generate-key
      run: echo "key=${{ inputs.key || runner.os }}-node-${{ hashFiles('**/package-lock.json') }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Restore Node.js modules cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path }}
        key: ${{ steps.generate-key.outputs.key }}
