export { ThemeDecorator } from '@/shared/config/storybook/ThemeDecorator'
export { PositionDecorator, DECORATOR_POSITION } from '@/shared/config/storybook/PositionDecorator/PositionDecorator'
export { withI18nDecorator } from '@/shared/config/storybook/withI18nDecorator'
export { RouterDecorator } from '@/shared/config/storybook/RouterDecorator'
export { SuspenseDecorator } from '@/shared/config/storybook/SuspenseDecorator'
