name: linting, testing, building
run-name: ${{ github.actor }} runs workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: install modules
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: linting typescript
        run: npm run lint
      - name: linting css
        run: npm run lint:scss

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: unit testing
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: build production project
        run: npm run build
      - name: Log results
        run: echo "Linting, testing, and building completed successfully."
