name: linting, testing, building
run-name: ${{ github.actor }} runs workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: ./github/actions/cache-node-modules
      - name: install modules
        run: npm ci --legacy-peer-deps

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Restore Node.js modules cache
        uses: ./github/actions/cache-node-modules
      - name: linting typescript
        run: npm run lint
      - name: linting css
        run: npm run lint:scss

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Restore Node.js modules cache
        uses: ./github/actions/cache-node-modules
      - name: unit testing
        run: npm run test:unit

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v4
      - name: Restore Node.js modules cache
        uses: ./github/actions/cache-node-modules
      - name: build production project
        run: npm run build
      - name: Log results
        run: echo "Linting, testing, and building completed successfully."
